# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AuthoApp' do
 
  use_frameworks!

  #FireBase
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Core'

  #Facebook
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  
  #Google
  pod 'GoogleSignIn'

end
